import { format } from "date-fns";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/Home.module.css";

type User = any;

async function searchUsers(query: string): Promise<User[]> {
  return fetch(`/api/users?q=${query}`).then((res) => res.json());
}

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState<User | null>(null);

  const [refetch, setRefetch] = useState(true);

  useEffect(() => {
    setLoading(true);
    searchUsers(query)
      .then((users) => setUsers(users))
      .finally(() => setLoading(false));
  }, [query, refetch]);

  useEffect(() => {
    // refetch results every 500ms
    const t = setInterval(() => setRefetch((prev) => !prev), 500);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {selected && <h1 data-testid="selected-user">{selected.name}</h1>}
        <form
          style={{ display: "flex", flexDirection: "column", gap: "8px" }}
          action=""
        >
          <input
            placeholder="search users"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />

          {loading && <div>Loading...</div>}
          {!loading &&
            users.length > 0 &&
            users.map((user) => (
              <button
                key={user.id}
                type="button"
                onClick={() => setSelected(user)}
              >
                {user.name}
              </button>
            ))}
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
